/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Conversor.Conversor;
import Conversor.EnumTemperatura;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author bruno.191196
 */
public class Interface extends javax.swing.JFrame {

  /** Creates new form Interface */
  public Interface() {
    initComponents();
    this.conversor = new Conversor();
    this.temperaturas = new HashMap<>();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    celsiusLabel = new javax.swing.JLabel();
    celsiusTextField = new javax.swing.JTextField();
    fahrenheitLabel = new javax.swing.JLabel();
    fahrenheitTextField = new javax.swing.JTextField();
    kelvinLabel = new javax.swing.JLabel();
    kelvinTextField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    salvarMenuItem = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    celsiusLabel.setText("Celsius");

    celsiusTextField.setText("Digite aqui uma temperatura em celsius");
    celsiusTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        celsiusTextFieldActionPerformed(evt);
      }
    });

    fahrenheitLabel.setText("Fahrenheit");

    fahrenheitTextField.setText("Digite aqui uma temperatura em fahrenheit");
    fahrenheitTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fahrenheitTextFieldActionPerformed(evt);
      }
    });

    kelvinLabel.setText("Kelvin");

    kelvinTextField.setText("Digite aqui uma temperatura em kelvin");
    kelvinTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        kelvinTextFieldActionPerformed(evt);
      }
    });

    jLabel4.setText("Digite um valor em um dos campos abaixo e a temperatura convertida será mostrada automaticamente nos outros campos");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(fahrenheitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
              .addComponent(kelvinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(celsiusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(celsiusTextField)
              .addComponent(fahrenheitTextField)
              .addComponent(kelvinTextField)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(celsiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(celsiusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(fahrenheitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fahrenheitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(kelvinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(kelvinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jMenu1.setText("Arquivo");

    salvarMenuItem.setText("Salvar");
    salvarMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        salvarMenuItemActionPerformed(evt);
      }
    });
    jMenu1.add(salvarMenuItem);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void celsiusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsiusTextFieldActionPerformed
    if (this.checagemEConversao(celsiusLabel.getText(), celsiusTextField.getText())) {
      this.setTextField();
    }    
  }//GEN-LAST:event_celsiusTextFieldActionPerformed

  private void fahrenheitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheitTextFieldActionPerformed
    if (this.checagemEConversao(fahrenheitLabel.getText(), fahrenheitTextField.getText())) {
      this.setTextField();
    } 
  }//GEN-LAST:event_fahrenheitTextFieldActionPerformed

  private void kelvinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelvinTextFieldActionPerformed
    if (this.checagemEConversao(kelvinLabel.getText(), kelvinTextField.getText())) {
      this.setTextField();
    } 
  }//GEN-LAST:event_kelvinTextFieldActionPerformed

  private void salvarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMenuItemActionPerformed
    conversor.salvar();
  }//GEN-LAST:event_salvarMenuItemActionPerformed

  private boolean checagemEConversao(String temperatura, String numero) {
    try {
      valor = Double.parseDouble(numero);
      temperaturas = conversor.converter(temperatura, valor);
      return true;
    }
    catch (NullPointerException e) {
      System.out.println("Você precisa digitar um valor para que ele possa ser transformado!");
    }
    catch (NumberFormatException e) {
      System.out.println("Valor inválido. Certifique-se de que está usando ponto ao invés de vírgula e que não haja outros tipos de caracteres além de números");
    }
    return false;
  }
  
  private void setTextField () {
    celsiusTextField.setText(temperaturas.get(EnumTemperatura.CELSIUS).toString());
    fahrenheitTextField.setText(temperaturas.get(EnumTemperatura.FAHRENHEIT).toString());
    kelvinTextField.setText(temperaturas.get(EnumTemperatura.KELVIN).toString());
  }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              if ("Nimbus".equals(info.getName())) {
                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  break;
              }
          }
      } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> {
        new Interface().setVisible(true);
      });
    }

  private final Conversor conversor;
  private Map<EnumTemperatura, Double> temperaturas;
  private double valor;
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel celsiusLabel;
  private javax.swing.JTextField celsiusTextField;
  private javax.swing.JLabel fahrenheitLabel;
  private javax.swing.JTextField fahrenheitTextField;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel kelvinLabel;
  private javax.swing.JTextField kelvinTextField;
  private javax.swing.JMenuItem salvarMenuItem;
  // End of variables declaration//GEN-END:variables

}
